# Generated by Django 4.0.2 on 2022-02-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('about', models.CharField(max_length=1000)),
                ('police_report', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('dor', models.DateTimeField(default=datetime.datetime.now)),
                ('help', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('cpassword', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
